version: "3.8"

networks:
  app-network:
    driver: bridge

services: 
  app:
    container_name: app
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: php-laravel
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes: 
      - ./:/var/www
    networks: 
      - app-network

  db:
    container_name: pgsql
    build:
      context: ./docker/pgsql
      dockerfile: Dockerfile
    image: pgsql-docker
    restart: unless-stopped
    expose:
     - "5432"
    ports:
      - "5433:5432"
    volumes: 
      - ./docker/pgsql/script:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports: 
        - 8080:80
    volumes: 
        - ./:/var/www
        - ./docker/nginx/conf:/etc/nginx/conf.d
    networks: 
        - app-network

  adminer:
    image: dockette/adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - '${FORWARD_ADMINER}:8080'
    networks: 
      - app-network
  
  redis:
    image: redis:alpine
    volumes:
      - ./docker/redis:/data
    ports:
      - "6379:6379"